name: Docker Publish

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: Build Latest Release with Maven
        if: ${{ ! github.event.release }}
        run: mvn --batch-mode --update-snapshots clean compile jib:build
            -Djib.to.auth.username=${{ github.actor }}
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
            -Djib.to.image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
